import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { defineConfig } from 'astro/config';
import tailwindcss from '@tailwindcss/vite';
import sitemap from '@astrojs/sitemap';

// The language list is shared with the pages (src/i18n/config.ts) and the scripts.
const languages = JSON.parse(readFileSync(new URL('./src/i18n/languages.json', import.meta.url), 'utf8'));
const siteUrl = readFileSync(new URL('./src/data/site.ts', import.meta.url), 'utf8').match(/url: '([^']+)'/)[1];
const [defaultLocale, ...otherLocales] = Object.keys(languages);
const htmlLang = Object.fromEntries(Object.entries(languages).map(([code, l]) => [code, l.htmlLang]));

const localeFallbacks = () => ({
  name: 'locale-fallbacks',
  hooks: {
    'astro:build:done': ({ dir }) => {
      const lines = ['# Generated by astro.config.mjs at build time. Do not edit.'];
      for (const locale of otherLocales) lines.push(`/${locale}/*  /${locale}/404/index.html  404`);
      lines.push('/*  /404/index.html  404');
      writeFileSync(fileURLToPath(new URL('_redirects', dir)), lines.join('\n') + '\n');
    },
  },
});

export default defineConfig({
  site: siteUrl,
  trailingSlash: 'always',
  i18n: { defaultLocale, locales: Object.keys(languages), routing: { prefixDefaultLocale: false } },
  integrations: [
    sitemap({ i18n: { defaultLocale, locales: htmlLang }, filter: (page) => !page.includes('/404') }),
    localeFallbacks(),
  ],
  vite: { plugins: [tailwindcss()] },
  build: { inlineStylesheets: 'auto' },
});
