// Derives the color tokens from a few decisions (hues, one lightness per role) and prints the CSS.
// For every hue it finds the highest chroma that still fits sRGB at the role's lightness, then caps it, so all
// hues carry the same visual weight. Paste the output into src/styles/global.css between the PALETTE markers,
// or run with --write to do that.   See docs/color-study.md.
import { readFileSync, writeFileSync } from 'node:fs';
import { clampChroma, formatHex } from 'culori';

// Four warm hues from the padlock body, left to right, and the one cool hue of the chip.
export const hues = { gold: 88, orange: 55, red: 27, magenta: 352, cyan: 215 };
const NEUTRAL = 355; // the logo's outline, a maroon so dark it reads as black

const fit = (l, c, h) => { const k = clampChroma({ mode: 'oklch', l, c, h }, 'oklch'); return `oklch(${l} ${Math.min(c, k.c).toFixed(3)} ${h})`; };
const roles = {
  light: { ink: [0.47, 0.16], soft: [0.955, 0.035] },
  dark: { ink: [0.83, 0.13], soft: [0.27, 0.06] },
};
// The logo's own colors: same in both themes, never used for text.
const vivid = { gold: [0.87, 0.16], orange: [0.76, 0.17], red: [0.66, 0.21], magenta: [0.62, 0.23], cyan: [0.84, 0.12] };

const neutrals = {
  light: { bg: [0.985, 0.005], surface: [1, 0], tint: [0.96, 0.01], line: [0.885, 0.014], text: [0.2, 0.03], muted: [0.45, 0.025] },
  dark: { bg: [0.145, 0.022], surface: [0.185, 0.026], tint: [0.225, 0.03], line: [0.33, 0.035], text: [0.955, 0.008], muted: [0.75, 0.02] },
};

function theme(name) {
  const out = [];
  for (const [k, [l, c]] of Object.entries(neutrals[name])) out.push(`  --${k}: ${fit(l, c, NEUTRAL)};`);
  for (const [k, h] of Object.entries(hues)) {
    out.push(`  --${k}: ${fit(...roles[name].ink, h)};`, `  --${k}-soft: ${fit(...roles[name].soft, h)};`);
  }
  return out.join('\n');
}
const shared = [
  ...Object.entries(hues).map(([k, h]) => `  --v-${k}: ${fit(...vivid[k], h)};`),
  `  --ink: ${fit(0.145, 0.022, NEUTRAL)};`, `  --ink-raised: ${fit(0.195, 0.028, NEUTRAL)};`, `  --ink-line: ${fit(0.33, 0.035, NEUTRAL)};`, `  --on-ink: ${fit(0.955, 0.008, NEUTRAL)};`, `  --on-ink-muted: ${fit(0.75, 0.02, NEUTRAL)};`,
  // The chip's cyan is the complement of the warm body, so one cyan button is the loudest thing on a page.
  // The deep end of the chip's gradient, and the veil behind dialogs.
  `  --v-cyan-deep: ${fit(0.7, 0.15, 245)};`, `  --veil: oklch(0.145 0.022 ${NEUTRAL} / 0.6);`, `  --shade: oklch(0 0 0 / 0.15);`,
  `  --action: ${fit(0.84, 0.12, 215)};`, `  --action-hi: ${fit(0.9, 0.1, 210)};`, `  --on-action: ${fit(0.2, 0.05, 235)};`,
].join('\n');

const css = `/* PALETTE:START generated by scripts/build-palette.mjs, do not edit by hand */
:root {
${shared}
${theme('light')}
}
[data-theme='dark'] {
${theme('dark')}
}
/* PALETTE:END */`;

if (process.argv.includes('--write')) {
  const file = new URL('../src/styles/global.css', import.meta.url);
  const src = readFileSync(file, 'utf8');
  writeFileSync(file, src.replace(/\/\* PALETTE:START[\s\S]*?PALETTE:END \*\//, css));
  console.log('palette written to src/styles/global.css');
} else console.log(css);
